
[project]
name = "smart-head"
version = "0.1.0"
description = "Test project for smart head detection"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lap==0.5.12",
    "ultralytics>=8.3.235",
]
